language: node_js
node_js:
  - "7"
os:
  - linux
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: ffd0f282963252fae4d9505b1b5deeb8abf27fa98326caa041ddfcabe99f7d5c
osx_image: xcode8
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
after_script: 
  - npm run codeclimate